# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Jest CI

on:
  push:
    branches:
      - heroku

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Jest test suite

    strategy:
      matrix:
        node-version: [22.10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test
        env:
          CI: true
